version: "3.9"

services:
  traefik:
    image: traefik:latest
    command:
      - "--accesslog"

      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.file.filename=/conf/traefik.yml"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.yml:/conf/traefik.yml"
      - "./certs:/certs"

  nginx:
    image: nginx:latest
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.web-nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.web-nginx.entrypoints=web"
      - "traefik.http.routers.web-nginx.service=nginx"

      - "traefik.http.routers.websecure-nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.websecure-nginx.entrypoints=websecure"
      - "traefik.http.routers.websecure-nginx.tls=true"
      - "traefik.http.routers.websecure-nginx.service=nginx"

      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.server.scheme=http"
