tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/localhost-cert.pem
        keyFile: /certs/localhost-key.pem

  certificates:
    - certFile: /certs/localhost-cert.pem
      keyFile: /certs/localhost-key.pem
      stores:
        - default

  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

    mintls13:
      minVersion: VersionTLS13
